### PR TITLE
chore: upgrade to Erlang 24

### PR DESCRIPTION
**Pull request by beatrixada**
Discovered that Mint 1.0.0 is broken on Erlang 24 due to `:ssl.cipher_suites/0` being removed while working with commuter_rail_boarding. Setup Dependabot, upgraded the deps, and removed the config file, which was empty.

### CODE REVIEW

**Comment by losvedir** [comment]
Hm, I don't think this is the right place to fix this. It's not really the job of the library to dictate what version of Elixir or Erlang the application uses. At most, it should specify its minimum version compatibility in `mix.exs`. However, [there's not currently a way](https://elixirforum.com/t/specifying-minimal-erlang-version-in-mix-exs/39911) to specify a minimum OTP version in an Elixir project. Elixir versions themselves have some minimum OTP requirements, but no Elixir versions right now require only OTP 24.

Even if there were a way to specify this, I don't think we'd want to pin `server_sent_event_stage` to OTP 24 - I'm sure there are lots of users of this library that aren't there yet!

If I understand the problem you're raising correctly, server_sent_event_stage has Mint as a dependency, and in commuter_rail_boarding it didn't work because Mint was trying to use an erlang function that was added in OTP 24? Something like that? What was the exact issue?

Mint [claims to support `elixir: "~> 1.5"`](https://github.com/elixir-mint/mint/blob/b706ba33dbabd5b4e137caafc1cd01c7228e0c70/mix.exs#L11), which in turn supports all the way back to OTP 18! I think this may be incorrect, honestly, and could probably use a PR over there. I found https://github.com/elixir-mint/mint/pull/293 , which claims to make it _compatible_ with OTP 24, but I'd be surprised if they made it require OTP 24.

Mint is a direct dependency of this library, and so it is the responsibility of this library to ensure its constraints are correct. Is there a version of Mint with a bug? I could see us needing to update `mix.exs` in this repo (not `mix.lock`, which is ignored when this is used as a library), to specify a version greater than the one with the bug.

**Comment by losvedir** [comment]
I just set up a little toy app locally using OTP 23 and Mint 1.4 and it was able to connect via TLS. So I'm not sure exactly what problem CRB had, but I don't think we need to change anything here.

**Comment by paulswartz** [comment]
@bklebe It looks like Mint 1.3 dropped use of `:ssl.cipher_suites/0`: we could update our `mix.exs` to depend on at least that version?

**Comment by beatrixada** [comment]
> If I understand the problem you're raising correctly, server_sent_event_stage has Mint as a dependency, and in commuter_rail_boarding it didn't work because Mint was trying to use an erlang function that was added in OTP 24? Something like that? What was the exact issue?

No, other way around. Mint 1.0 uses a deprecated Erlang function (`:ssl.cipher_suites/0`) that was removed in Erlang 24, and CRB installed Mint 1.0 when I ran `mix deps.get`.

I had no intentions of enforcing the version of Erlang being used for downstream consumers, I just wanted to make this library compatible with Erlang 24. I also did not realize `mix.lock` worked like that, I just ran `mix deps.update mint`. Maybe it's possible to get `commuter_rail_boarding` to use a newer version of Mint without updating the `mix.exs` though, since in theory 1.3 fits the constraint? In which case this PR is unnecessary.

**Comment by beatrixada** [comment]
Yeah, I just needed to run `mix deps.update mint` in CRB. I had just totally forgotten that `mix.lock` exists to be able to fix things like this downstream and share the result.

**Pull request closed without merging**
